huginn/config/routes.rb
Rails.application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      put :leave_scenario
      post :reemit_events
      delete :remove_events
      delete :memory, action: :destroy_memory
    end

    collection do
      put :toggle_visibility
      post :propagate
      get :type_details
      get :event_descriptions
      post :validate
      post :complete
      delete :undefined, action: :destroy_undefined
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end

    resources :events, :only => [:index]

    scope module: :agents do
      resources :dry_runs, only: [:index, :create]
    end
  end

  scope module: :agents do
    resources :dry_runs, only: [:index, :create]
  end

  resource :diagram, :only => [:show]

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :scenarios do
    collection do
      resource :scenario_imports, :only => [:new, :create]
    end

    member do
      get :share
      get :export
      put :enable_or_disable_all_agents
    end

    resource :diagram, :only => [:show]
  end

  resources :user_credentials, :except => :show do
    collection do
      post :import
    end
  end

  resources :services, :only => [:index, :destroy] do
    member do
      post :toggle_availability
    end
  end

  resources :jobs, :only => [:index, :destroy] do
    member do
      put :run
    end
    collection do
      delete :destroy_failed
      delete :destroy_all
      post :retry_queued
    end
  end

  namespace :admin do
    resources :users, except: :show do
      member do
        put :deactivate
        put :activate
        get :switch_to_user
      end
      collection do
        get :switch_back
      end
    end
  end

  get "/worker_status" => "worker_status#show"

  match "/users/:user_id/web_requests/:agent_id/:secret" => "web_requests#handle_request", :as => :web_requests, :via => [:get, :post, :put, :delete]
  post  "/users/:user_id/webhooks/:agent_id/:secret" => "web_requests#handle_request" # legacy
  post  "/users/:user_id/update_location/:secret" => "web_requests#update_location" # legacy

  devise_for :users,
             controllers: {
               omniauth_callbacks: 'omniauth_callbacks',
               registrations: 'users/registrations'
             },
             sign_out_via: [:post, :delete]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "/about" => "home#about"
  root :to => "home#index"
end

huginn/app/models/event.rb
require 'location'

# Events are how Huginn Agents communicate and log information about the world.  Events can be emitted and received by
# Agents.  They contain a serialized `payload` of arbitrary JSON data, as well as optional `lat`, `lng`, and `expires_at`
# fields.
class Event < ActiveRecord::Base
  include JsonSerializedField
  include LiquidDroppable

  acts_as_mappable

  json_serialize :payload

  belongs_to :user, optional: true
  belongs_to :agent, counter_cache: true

  has_many :agent_logs_as_inbound_event, class_name: "AgentLog", foreign_key: :inbound_event_id,
                                         dependent: :nullify
  has_many :agent_logs_as_outbound_event, class_name: "AgentLog", foreign_key: :outbound_event_id,
                                          dependent: :nullify

  scope :recent, lambda { |timespan = 12.hours.ago|
    where("events.created_at > ?", timespan)
  }

  after_create :update_agent_last_event_at
  after_create :possibly_propagate

  scope :expired, lambda {
    where("expires_at IS NOT NULL AND expires_at < ?", Time.now)
  }

  case ActiveRecord::Base.connection.adapter_name
  when /\Amysql/i
    # Protect the Event table from InnoDB's AUTO_INCREMENT Counter
    # Initialization by always keeping the latest event.
    scope :to_expire, -> { expired.where.not(id: maximum(:id)) }
  else
    scope :to_expire, -> { expired }
  end

  scope :with_location, -> {
    where.not(lat: nil).where.not(lng: nil)
  }

  def location
    @location ||= Location.new(
      # lat and lng are BigDecimal, but converted to Float by the Location class
      lat:,
      lng:,
      radius:
        if (h = payload[:horizontal_accuracy].presence) &&
            (v = payload[:vertical_accuracy].presence)
          (h.to_f + v.to_f) / 2
        else
          (h || v || payload[:accuracy]).to_f
        end,
      course: payload[:course],
      speed: payload[:speed].presence
    )
  end

  def location=(location)
    case location
    when nil
      self.lat = self.lng = nil
      return
    when Location
    else
      location = Location.new(location)
    end
    self.lat = location.lat
    self.lng = location.lng
    location
  end

  # Emit this event again, as a new Event.
  def reemit!
    agent.create_event(payload:, lat:, lng:)
  end

  # Look for Events whose `expires_at` is present and in the past.  Remove those events and then update affected Agents'
  # `events_counts` cache columns.  This method is called by bin/schedule.rb periodically.
  def self.cleanup_expired!
    transaction do
      affected_agents = Event.expired.group("agent_id").pluck(:agent_id)
      Event.to_expire.delete_all
      Agent.where(id: affected_agents).update_all "events_count = (select count(*) from events where agent_id = agents.id)"
    end
  end

  protected

  def update_agent_last_event_at
    agent.touch :last_event_at
  end

  def possibly_propagate
    # immediately schedule agents that want immediate updates
    propagate_ids = agent.receivers.where(propagate_immediately: true).pluck(:id)
    Agent.receive!(only_receivers: propagate_ids) unless propagate_ids.empty?
  end

  public def to_liquid
    Drop.new(self)
  end

  class Drop < LiquidDroppable::Drop
    def initialize(object)
      @payload = object.payload
      super
    end

    def liquid_method_missing(key)
      @payload[key]
    end

    def each(&block)
      @payload.each(&block)
    end

    def agent
      @payload.fetch(__method__) {
        @object.agent
      }
    end

    def created_at
      @payload.fetch(__method__) {
        @object.created_at
      }
    end

    def _location_
      @object.location
    end

    def as_json
      {
        location: _location_.as_json,
        agent: @object.agent.to_liquid.as_json,
        payload: @payload.as_json,
        created_at: created_at.as_json
      }
    end
  end
end

huginn/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :load_event, except: [:index, :show]

  def index
    if params[:agent_id]
      @agent = current_user.agents.find(params[:agent_id])
      @events = @agent.events.page(params[:page])
    else
      @events = current_user.events.preload(:agent).page(params[:page])
    end

    respond_to do |format|
      format.html
      format.json { render json: @events }
    end
  end

  def show
    respond_to do |format|
      format.html do
        load_event
      rescue ActiveRecord::RecordNotFound
        return_to = params[:return] or raise
        redirect_to return_to, allow_other_host: false
      end
      format.json { render json: @event }
    end
  end

  def reemit
    @event.reemit!
    respond_to do |format|
      format.html { redirect_back event_path(@event), notice: 'Event re-emitted.' }
    end
  end

  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_back events_path, notice: 'Event deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def load_event
    @event = current_user.events.find(params[:id])
  end
end

huginn/app/views/events/index.html.erb
<% content_for :title, (@agent ? @agent.name + "'s " : "") + "Events" -%>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <span class='h2'>
          Your Events
          <% if @agent %>
            from <%= @agent.name %>
          <% end %>
        </span>
        <% if @agent %>
          <%= render 'agents/mini_action_menu', agent: @agent, return_to: request.path %>
        <% end %>
      </div>

      <div class='table-responsive'>
        <table class='table table-striped events'>
          <tr>
            <% unless @agent %>
              <th>Source</th>
            <% end %>
            <th>Created</th>
            <th>Payload</th>
            <th></th>
          </tr>

        <% @events.each do |event| %>
          <% next unless event.agent %>
          <%= content_tag :tr, class: (highlighted?(event.id) ? 'hl' : nil) do %>
            <% unless @agent %>
              <td><%= link_to event.agent.name, agent_path(event.agent, return: request.fullpath) %></td>
            <% end %>
            <td title='<%= event.created_at %>'><%= time_ago_in_words event.created_at %> ago</td>
            <td class='payload'><%= truncate event.payload.to_json, :length => 90, :omission => "" %></td>
            <td>
              <div class="btn-group btn-group-xs">
                <%= link_to 'Show', event_path(event, return: request.fullpath), class: "btn btn-default" %>
                <%= link_to 'Re-emit', reemit_event_path(event), method: :post, data: { confirm: 'Are you sure you want to duplicate this event and emit the new one now?' }, class: "btn btn-default" %>
                <%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
              </div>
            </td>
          <% end %>
        <% end %>
        </table>
      </div>

      <%= paginate @events, params: params.to_unsafe_h.slice(:hl), theme: 'twitter-bootstrap-3' %>

      <br />

      <% if @agent %>
        <div class="btn-group">
          <%= link_to icon_tag('glyphicon-chevron-left') + ' Back'.html_safe, filtered_agent_return_link || agents_path, class: "btn btn-default" %>
          <%= link_to icon_tag('glyphicon-random') + ' See all events'.html_safe, events_path, class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

huginn/app/views/events/show.html.erb
<% content_for :title, "Event " + @event.id.to_s -%>

<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <div class="page-header">
        <span class='h2'>
          Event from <%= @event.agent.name %>
        </span>
        <%= render 'agents/mini_action_menu', agent: @event.agent, return_to: event_path(@event) %>
      </div>

      <p>
        <b>Expires in:</b>
        <%= @event.expires_at ? time_ago_in_words(@event.expires_at) : 'never' %>
      </p>

      <p>
        <b>Payload:</b>
        <pre><%= Utils.pretty_jsonify @event.payload || {} %></pre>
      </p>

      <% if @event.lat && @event.lng %>
        <% content_for :head do -%>
<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{@event.agent.options[:api_key]}" %>
<%= javascript_include_tag "map_marker" %>
        <% end -%>

        <p>
          <b>Lat:</b>
          <%= @event.lat %>
          <br/>
          <b>Lng:</b>
          <%= @event.lng %>
        </p>

        <div id="map_canvas" style="width:400px; height:300px"></div>

        <script type="text/javascript">
          var mapOptions = {
            center: new google.maps.LatLng(<%= @event.lat %>, <%= @event.lng %>),
            zoom:15,
            mapTypeId:google.maps.MapTypeId.ROADMAP
          };

          var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);

          map_marker(map, <%= Utils.jsonify(@event.location) %>);
        </script>
      <% end %>

      <br />
      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back'.html_safe, filtered_agent_return_link || events_path, class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-refresh') + ' Re-emit', reemit_event_path(@event), method: :post, data: { confirm: 'Are you sure you want to duplicate this event and emit the new one now?' }, class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-remove', class: 'color-danger') + ' Delete', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>